### ISSUE TITLE
PyPI?

### ISSUE THREAD

**Issue by thetylerhayes** [martinkosir/neverbounce-python#1]
i noticed there's a testpypi page for this lib but not a production one: https://testpypi.python.org/pypi/neverbounce/0.1.1

any plans to let us pip install?

**Comment by martinkosir** [comment]
I am going to release the package this week.

**Comment by martinkosir** [comment]
I released the package today (https://pypi.python.org/pypi/neverbounce).
Any feedback or bug reports would be highly appreciated.

Installation:

```
pip install neverbounce
```
